# Generated by Django 5.0.2 on 2024-02-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('body', models.TextField()),
                ('author', models.TextField()),
                ('datetime_posted', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
